### Paths ###
# MacPorts
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
export MANPATH=/opt/local/share/man:$MANPATH
# bin folders
if [ -d ~/bin ]; then
	export PATH=:~/bin:$PATH  # add your bin folder to the path
fi
if [ -d ~/.cl/bin ]; then
	export PATH=:~/.cl/bin:$PATH  # add your cl/bin folder to the path
fi
# MySQL
export PATH=$PATH:/usr/local/mysql/bin
# TeX
export PATH=$PATH:/usr/texbin

### Gem Path ###
export GEM_HOME=/Library/Ruby/Gems/1.8
export GEM_PATH=/Library/Ruby/Gems/1.8:~/.gem/ruby/1.8

