### BASHRC ###
source ~/.bashrc

### Colors ###
export TERM=xterm-color
export GREP_OPTIONS='--color=auto' GREP_COLOR='1;32'
export CLICOLOR=1

### History ###
export HISTCONTROL=ignoredups
export HISTCONTROL=erasedups
export HISTFILESIZE=3000
export HISTIGNORE="ls:cd:[bf]g:exit:..:...:ll:lla"
alias h=history

### Editors ###
export EDITOR="gvim"
export VIM_APP_DIR="/Applications/Editors"

### Completion ###
if [ -f /opt/local/etc/bash_completion ]; then
. /opt/local/etc/bash_completion
fi

### Notes ###
# When you start an interactive shell (log in, open terminal or iTerm in OS X, 
# or create a new tab in iTerm) the following files are read and run, in this order:
#     profile
#     bashrc
#     .bash_profile
#     .bashrc (only because this file is run (sourced) in .bash_profile)
#
# When an interactive shell, that is not a login shell, is started 
# (when you run "bash" from inside a shell, or when you start a shell in 
# xwindows [xterm/gnome-terminal/etc] ) the following files are read and executed, 
# in this order:
#     bashrc
#     .bashrc

