### Paths ###
# MacPorts
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
export MANPATH=/opt/local/share/man:$MANPATH
# bin folders
if [ -d ~/bin ]; then
	export PATH=:~/bin:$PATH  # add your bin folder to the path
fi
if [ -d ~/.cl/bin ]; then
	export PATH=:~/.cl/bin:$PATH  # add your cl/bin folder to the path
fi
# MySQL
export PATH=$PATH:/usr/local/mysql/bin

### BASHRC ###
source ~/.bashrc

### Notes ###
# When you start an interactive shell (log in, open terminal or iTerm in OS X, 
# or create a new tab in iTerm) the following files are read and run, in this order:
#     profile
#     bashrc
#     .bash_profile
#     .bashrc (only because this file is run (sourced) in .bash_profile)
#
# When an interactive shell, that is not a login shell, is started 
# (when you run "bash" from inside a shell, or when you start a shell in 
# xwindows [xterm/gnome-terminal/etc] ) the following files are read and executed, 
# in this order:
#     bashrc
#     .bashrc

