set nocompatible

" Colors
"set t_Co=256
set background=dark
syntax on
filetype plugin indent on
colorscheme zenburn
set hlsearch

" Editing
set autowrite			" save file when compiling, switching windows, etc.
set backspace=indent,eol,start	" backspace over anything
set expandtab			" use space, not tab characters
set tabstop=4			" set tabs to a width of 4
set softtabstop=4		" set soft tabs to a width of 4
set shiftwidth=4		" shifts over whitespace in 4-s
set autoindent			" turn on autoindenting
set number              " turn on line numbers

" Use Rake
set makeprg=rake

" Latex Suite
" Force grep to always display the filename to avoid confusing Latex Suite
set grepprg=grep\ -nH\ $*
" Load .tex files as latex, not plaintex
let g:tex_flavor='latex'
" Compile pdfs multiple times
let g:Tex_MultipleCompileFormats+=',pdf'
" Use XeLaTeX
let g:Tex_CompileRule_pdf = 'xelatex --interaction=nonstopmode $*'
